### ISSUE TITLE
Giant error dump when I try to authorize a MediaGoblin

### ISSUE THREAD

**Issue by kozross** [xray7224/p#35]
I found this tool at the direction of #mediagoblin, with the aim of being able to upload videos to [this MediaGoblin instance](https://goblinrefuge.com/mediagoblin/) as the user `kozross`. Having set it up (including the virtualenv stuff etc), I tried running this command:

```
p authorize kozross@goblinrefuge.com
```

I got this error dump:

```
Traceback (most recent call last):
  File "/home/koz/p/lib/python3.4/site-packages/pypump/client.py", line 149, in request
server_data = response.json()
  File "/home/koz/p/lib/python3.4/site-packages/requests/models.py", line 819, in json
return json.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/koz/p/bin/p", line 6, in <module>
exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/koz/p/p", line 962, in <module>
cli()
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 700, in __call__
return self.main(*args, **kwargs)
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 680, in main
rv = self.invoke(ctx)
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 873, in invoke
return ctx.invoke(self.callback, **ctx.params)
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 508, in invoke
return callback(*args, **kwargs)
  File "/home/koz/p/lib/python3.4/site-packages/click/decorators.py", line 63, in new_func
return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/koz/p/lib/python3.4/site-packages/click/core.py", line 508, in invoke
return callback(*args, **kwargs)
  File "/home/koz/p/p", line 348, in p_authorize
verify_requests=p.settings["verify_ssl_certs"]
  File "/home/koz/p/lib/python3.4/site-packages/pypump/pypump.py", line 503, in __init__
super(WebPump, self).__init__(*args, **kwargs)
  File "/home/koz/p/lib/python3.4/site-packages/pypump/pypump.py", line 120, in __init__
self.client.register()
  File "/home/koz/p/lib/python3.4/site-packages/pypump/client.py", line 169, in register
server_data = self.request(server)
  File "/home/koz/p/lib/python3.4/site-packages/pypump/client.py", line 151, in request
raise ClientException(response.content)
pypump.client.ClientException: b'<?xml version="1.0" encoding="iso-8859-1"?>\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\n         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">\n <head>\n  <title>404 - Not Found</title>\n </head>\n <body>\n  <h1>404 - Not Found</h1>\n </body>\n</html>\n'
```

Did I do something stupid, or is something genuinely wrong here?

**Comment by xray7224** [comment]
Something is wrong with the Mediagoblin instance and not p, I will do my best to look into it though, would be useful to have the server logs of this happening though I will try to reproduce.

**Comment by kozross** [comment]
@xray7224 I'd love to give you the logs, but I don't host the instance in question, and I've had no luck trying to contact the person who does, unfortunately.

**Comment by ayleph** [comment]
@kozross The correct API URL for Goblin Refuge is pump.goblinrefuge.com. This isn't advertised. It works for a number of pump clients (Dianara, Pumpa, Goblinoid), so it probably works for p as well.

**Comment by moggers87** [comment]
I guess we can close this as it's nothing to do with `p`.
